language: python

install: skip

script:
  - echo "No tests. Just deploying to PyPI."

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master
    tags: true
