language: python
python:
  - 3.8

install:
  - pip3 install -U -r tests/requirements.txt

# if: tag IS present

script:
  - echo "For debugging: branch=$TRAVIS_BRANCH hash=$TRAVIS_COMMIT"
  - echo "\nPython Code Coverage\n========================================"
  - coverage run --append -m unittest tests.unit.Attributes
#  - coverage run --append -m unittest tests.unit.ArgParse
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
  - echo "\nPython Unit Tests\n========================================"
  - python -m unittest tests.unit.Attributes
#  - python -m unittest tests.unit.ArgParse

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
